# Generated by Django 5.1.5 on 2025-02-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='blank', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='blank')),
                ('image', models.ImageField(default='blank', null=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='blank', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('number', models.IntegerField(default=0)),
                ('password', models.IntegerField(default='')),
            ],
        ),
    ]
