# Generated by Django 5.1.5 on 2025-02-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
