# Generated by Django 5.1.5 on 2025-02-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_foods_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='offer',
        ),
    ]
