# Generated by Django 5.1.5 on 2025-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_remove_foods_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ownerlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='blank', max_length=30)),
                ('password', models.IntegerField(default='')),
            ],
        ),
    ]
