# Generated by Django 5.1.5 on 2025-02-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_ownerlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ownerlogin',
            new_name='ownerinfo',
        ),
    ]
