# Generated by Django 5.1.5 on 2025-02-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_userinfo_address_userinfo_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='extrauserinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='blank', max_length=100)),
                ('number', models.IntegerField(max_length=10, null=True)),
                ('address', models.TextField(default='blank')),
                ('pin', models.IntegerField(max_length=6, null=True)),
                ('password', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
