# Generated by Django 5.1.5 on 2025-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_extrauserinfo_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserinfo',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='extrauserinfo',
            name='pin',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
