# Generated by Django 5.1.5 on 2025-02-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_alter_extrauserinfo_number_alter_extrauserinfo_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauserinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
