# Generated by Django 5.1.5 on 2025-02-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_extrauserinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrauserinfo',
            name='password',
        ),
    ]
