# Generated by Django 5.1.5 on 2025-03-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_remove_extrauserinfo_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ownerinfo',
        ),
    ]
