# Generated by Django 5.0.6 on 2025-06-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_delete_ownerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='blank', max_length=100)),
                ('address', models.TextField(default='blank', max_length=500)),
                ('order', models.TextField(default='blank', max_length=1000)),
            ],
        ),
    ]
